# -*- coding: utf-8 -*-
"""hello 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TKlTCsMOhUVOhihB-9jxQI6KI6d3uMbv
"""

print("bye")
print("hello again")