# -*- coding: utf-8 -*-
"""hello.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dyfIHHGCF_IfYcv0MI7CFTHo1idbJkSd
"""

print("hello world")